### ISSUE TITLE
Where's your .gitignore?

### ISSUE THREAD

**Issue by artlogic** [lewisde/Adventure#8]

**Comment by artlogic** [comment]
Again - it's considered best practice to close an issue by tying a commit to it - generally by referencing the issue in the commit message.

**Comment by lewisde** [comment]
Okay. I'll remember that for future issues.

I wasn't sure where they would be connected. It will also mean that my
changes will become more atomic.

I had some comments about my commits at AT&T also.

Again - it's considered best practice to close an issue by tying a commit
to it - generally by referencing the issue in the commit message.

**Comment by artlogic** [comment]
In Github, the commit will link to the issue and the issue to the commit. It provides trace-ability. You should give it a try, it's actually pretty cool.
