### ISSUE TITLE
More naming hints

### ISSUE THREAD

**Issue by artlogic** [lewisde/Adventure#9]
If you change this sort of a project structure, things will be a bit nicer:

```
├── adventure
│   ├── __init__.py
│   ├── classes.py
│   └── map.py
└── main.py
```

Then you can do this:

``` python
from adventure import map
from adventure.classes import Room
```

Another optimization might be putting your classes in the module init so you could just do this:

``` python
from adventure import Room
```

Like Guido says:

> Namespaces are one honking great idea -- let's do more of those!

**Comment by lewisde** [comment]
Looks like I had a circular import. classes imports map, map imports
classes, and main imports classes.

I'll have to rewrite some references to map and read up on __init_.py
before the next commit.

David
